[versions]
androidx-annotation = "1.2.0"
androidx-appcompat = "1.2.0"
androidx-constraintlayout = "2.0.4"
androidx-core = "1.3.2"
androidx-lifecycle-extensions = "2.2.0"
androidx-lifecycle-livedata = "2.3.1"
androidx-lifecycle-runtime = "2.3.1"
androidx-lifecycle-viewmodel = "2.3.1"
androidx-localbroadcastmanager = "1.0.0"
androidx-navigation = "2.3.5"
androidx-test-junit = "1.1.2"
androidx-test-monitor = "1.3.0"
androidx-test-runner = "1.3.0"
androidx-work = "2.5.0"
assaabloy-android-testutil = "0.8.0"
desugar-jdk-libs = "1.1.1"
google-material = "1.3.0"
google-playCore = "1.8.1"
junit = "4.13.2"
kotlinx-coroutinesTest = "1.4.0"
kotlinx-serialization = "1.0.0"
materialdaypicker = "0.7.4"
okhttp = "4.9.0"
robolectric = "4.5.1"
yahooFinance = "3.15.0"

[libraries]
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidxLocalbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }
androidxConstraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidxLifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidxLifecycleLivedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-livedata" }
androidxLifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidxLifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel" }
androidxNavigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidxNavigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidxTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidxTestMonitor = { module = "androidx.test:monitor", version.ref = "androidx-test-monitor" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidxWorkRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidxWorkTesting = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
assaabloyAndroidTestutil = { module = "com.assaabloy.stg.android:testutil", version.ref = "assaabloy-android-testutil" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "google-material" }
googlePlayCore = { module = "com.google.android.play:core-ktx", version.ref = "google-playCore" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutinesTest" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
materialdaypicker = { module = "ca.antonious:materialdaypicker", version.ref = "materialdaypicker" }
okhttpOkhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttpMockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
yahooFinance = { module = "com.yahoofinance-api:YahooFinanceAPI", version.ref = "yahooFinance" }
